export interface Country {
  name: string;
  code: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: 'Argentina', code: 'ARG', flag: '🇦🇷' },
  { name: 'Australia', code: 'AUS', flag: '🇦🇺' },
  { name: 'Austria', code: 'AUT', flag: '🇦🇹' },
  { name: 'Belgium', code: 'BEL', flag: '🇧🇪' },
  { name: 'Brazil', code: 'BRA', flag: '🇧🇷' },
  { name: 'Cameroon', code: 'CMR', flag: '🇨🇲' },
  { name: 'Canada', code: 'CAN', flag: '🇨🇦' },
  { name: 'Chile', code: 'CHI', flag: '🇨🇱' },
  { name: 'Colombia', code: 'COL', flag: '🇨🇴' },
  { name: 'Costa Rica', code: 'CRC', flag: '🇨🇷' },
  { name: 'Croatia', code: 'CRO', flag: '🇭🇷' },
  { name: 'Czech Republic', code: 'CZE', flag: '🇨🇿' },
  { name: 'Denmark', code: 'DEN', flag: '🇩🇰' },
  { name: 'Ecuador', code: 'ECU', flag: '🇪🇨' },
  { name: 'Egypt', code: 'EGY', flag: '🇪🇬' },
  { name: 'England', code: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { name: 'France', code: 'FRA', flag: '🇫🇷' },
  { name: 'Germany', code: 'GER', flag: '🇩🇪' },
  { name: 'Ghana', code: 'GHA', flag: '🇬🇭' },
  { name: 'Greece', code: 'GRE', flag: '🇬🇷' },
  { name: 'Iran', code: 'IRN', flag: '🇮🇷' },
  { name: 'Italy', code: 'ITA', flag: '🇮🇹' },
  { name: 'Ivory Coast', code: 'CIV', flag: '🇨🇮' },
  { name: 'Japan', code: 'JPN', flag: '🇯🇵' },
  { name: 'Mexico', code: 'MEX', flag: '🇲🇽' },
  { name: 'Morocco', code: 'MAR', flag: '🇲🇦' },
  { name: 'Netherlands', code: 'NED', flag: '🇳🇱' },
  { name: 'Nigeria', code: 'NGA', flag: '🇳🇬' },
  { name: 'Norway', code: 'NOR', flag: '🇳🇴' },
  { name: 'Paraguay', code: 'PAR', flag: '🇵🇾' },
  { name: 'Peru', code: 'PER', flag: '🇵🇪' },
  { name: 'Poland', code: 'POL', flag: '🇵🇱' },
  { name: 'Portugal', code: 'POR', flag: '🇵🇹' },
  { name: 'Republic of Ireland', code: 'IRL', flag: '🇮🇪' },
  { name: 'Romania', code: 'ROU', flag: '🇷🇴' },
  { name: 'Saudi Arabia', code: 'KSA', flag: '🇸🇦' },
  { name: 'Scotland', code: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { name: 'Senegal', code: 'SEN', flag: '🇸🇳' },
  { name: 'Serbia', code: 'SRB', flag: '🇷🇸' },
  { name: 'South Korea', code: 'KOR', flag: '🇰🇷' },
  { name: 'Spain', code: 'ESP', flag: '🇪🇸' },
  { name: 'Sweden', code: 'SWE', flag: '🇸🇪' },
  { name: 'Switzerland', code: 'SUI', flag: '🇨🇭' },
  { name: 'Turkey', code: 'TUR', flag: '🇹🇷' },
  { name: 'Ukraine', code: 'UKR', flag: '🇺🇦' },
  { name: 'United States', code: 'USA', flag: '🇺🇸' },
  { name: 'Uruguay', code: 'URU', flag: '🇺🇾' },
  { name: 'Wales', code: 'WAL', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' }
].sort((a, b) => a.name.localeCompare(b.name));
