export interface Country {
  name: string;
  code: string;
  flag: string;
  elo: number;
}

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', elo: 35 },
  { name: 'Åland Islands', code: 'AX', flag: '🇦🇽', elo: 47 },
  { name: 'Albania', code: 'AL', flag: '🇦🇱', elo: 72 },
  { name: 'Algeria', code: 'DZ', flag: '🇩🇿', elo: 78 },
  { name: 'American Samoa', code: 'AS', flag: '🇦🇸', elo: 32 },
  { name: 'Andorra', code: 'AD', flag: '🇦🇩', elo: 40 },
  { name: 'Angola', code: 'AO', flag: '🇦🇴', elo: 31 },
  { name: 'Anguilla', code: 'AI', flag: '🇦🇮', elo: 59 },
  { name: 'Antarctica', code: 'AQ', flag: '🇦🇶', elo: 42 },
  { name: 'Antigua and Barbuda', code: 'AG', flag: '🇦🇬', elo: 34 },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷', elo: 96 },
  { name: 'Armenia', code: 'AM', flag: '🇦🇲', elo: 45 },
  { name: 'Aruba', code: 'AW', flag: '🇦🇼', elo: 39 },
  { name: 'Australia', code: 'AU', flag: '🇦🇺', elo: 79 },
  { name: 'Austria', code: 'AT', flag: '🇦🇹', elo: 80 },
  { name: 'Azerbaijan', code: 'AZ', flag: '🇦🇿', elo: 38 },
  { name: 'Bahamas (The)', code: 'BS', flag: '🇧🇸', elo: 56 },
  { name: 'Bahrain', code: 'BH', flag: '🇧🇭', elo: 66 },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', elo: 57 },
  { name: 'Barbados', code: 'BB', flag: '🇧🇧', elo: 39 },
  { name: 'Belarus', code: 'BY', flag: '🇧🇾', elo: 46 },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪', elo: 90 },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿', elo: 42 },
  { name: 'Benin', code: 'BJ', flag: '🇧🇯', elo: 37 },
  { name: 'Bermuda', code: 'BM', flag: '🇧🇲', elo: 61 },
  { name: 'Bhutan', code: 'BT', flag: '🇧🇹', elo: 41 },
  { name: 'Bolivia (Plurinational State of)', code: 'BO', flag: '🇧🇴', elo: 35 },
  { name: 'Bonaire, Sint Eustatius and Saba', code: 'BQ', flag: '🇧🇶', elo: 62 },
  { name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦', elo: 71 },
  { name: 'Botswana', code: 'BW', flag: '🇧🇼', elo: 60 },
  { name: 'Bouvet Island', code: 'BV', flag: '🇧🇻', elo: 33 },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷', elo: 94 },
  { name: 'British Indian Ocean Territory (the)', code: 'IO', flag: '🇮🇴', elo: 63 },
  { name: 'Brunei Darussalam', code: 'BN', flag: '🇧🇳', elo: 41 },
  { name: 'Bulgaria', code: 'BG', flag: '🇧🇬', elo: 42 },
  { name: 'Burkina Faso', code: 'BF', flag: '🇧🇫', elo: 72 },
  { name: 'Burundi', code: 'BI', flag: '🇧🇮', elo: 57 },
  { name: 'Cabo Verde', code: 'CV', flag: '🇨🇻', elo: 30 },
  { name: 'Cambodia', code: 'KH', flag: '🇰🇭', elo: 41 },
  { name: 'Cameroon', code: 'CM', flag: '🇨🇲', elo: 76 },
  { name: 'Canada', code: 'CA', flag: '🇨🇦', elo: 76 },
  { name: 'Cayman Islands (the)', code: 'KY', flag: '🇰🇾', elo: 33 },
  { name: 'Central African Republic (the)', code: 'CF', flag: '🇨🇫', elo: 46 },
  { name: 'Chad', code: 'TD', flag: '🇹🇩', elo: 37 },
  { name: 'Chile', code: 'CL', flag: '🇨🇱', elo: 76 },
  { name: 'China', code: 'CN', flag: '🇨🇳', elo: 65 },
  { name: 'Christmas Island', code: 'CX', flag: '🇨🇽', elo: 58 },
  { name: 'Cocos (Keeling) Islands (the)', code: 'CC', flag: '🇨🇨', elo: 63 },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴', elo: 86 },
  { name: 'Comoros (the)', code: 'KM', flag: '🇰🇲', elo: 59 },
  { name: 'Congo (the Democratic Republic of the)', code: 'CD', flag: '🇨🇩', elo: 64 },
  { name: 'Congo (the)', code: 'CG', flag: '🇨🇬', elo: 42 },
  { name: 'Cook Islands (the)', code: 'CK', flag: '🇨🇰', elo: 58 },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', elo: 75 },
  { name: 'Côte d\'Ivoire', code: 'CI', flag: '🇨🇮', elo: 41 },
  { name: 'Croatia', code: 'HR', flag: '🇭🇷', elo: 88 },
  { name: 'Cuba', code: 'CU', flag: '🇨🇺', elo: 59 },
  { name: 'Curaçao', code: 'CW', flag: '🇨🇼', elo: 36 },
  { name: 'Cyprus', code: 'CY', flag: '🇨🇾', elo: 37 },
  { name: 'Czechia', code: 'CZ', flag: '🇨🇿', elo: 76 },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰', elo: 82 },
  { name: 'Djibouti', code: 'DJ', flag: '🇩🇯', elo: 57 },
  { name: 'Dominica', code: 'DM', flag: '🇩🇲', elo: 30 },
  { name: 'Dominican Republic (the)', code: 'DO', flag: '🇩🇴', elo: 34 },
  { name: 'Ecuador', code: 'EC', flag: '🇪🇨', elo: 79 },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬', elo: 77 },
  { name: 'El Salvador', code: 'SV', flag: '🇸🇻', elo: 68 },
  { name: 'Equatorial Guinea', code: 'GQ', flag: '🇬🇶', elo: 44 },
  { name: 'Eritrea', code: 'ER', flag: '🇪🇷', elo: 63 },
  { name: 'Estonia', code: 'EE', flag: '🇪🇪', elo: 31 },
  { name: 'Eswatini', code: 'SZ', flag: '🇸🇿', elo: 65 },
  { name: 'Ethiopia', code: 'ET', flag: '🇪🇹', elo: 30 },
  { name: 'Falkland Islands (the) [Malvinas]', code: 'FK', flag: '🇫🇰', elo: 51 },
  { name: 'Faroe Islands (the)', code: 'FO', flag: '🇫🇴', elo: 55 },
  { name: 'Fiji', code: 'FJ', flag: '🇫🇯', elo: 42 },
  { name: 'Finland', code: 'FI', flag: '🇫🇮', elo: 74 },
  { name: 'France', code: 'FR', flag: '🇫🇷', elo: 95 },
  { name: 'French Guiana', code: 'GF', flag: '🇬🇫', elo: 43 },
  { name: 'French Polynesia', code: 'PF', flag: '🇵🇫', elo: 56 },
  { name: 'French Southern Territories (the)', code: 'TF', flag: '🇹🇫', elo: 57 },
  { name: 'Gabon', code: 'GA', flag: '🇬🇦', elo: 46 },
  { name: 'Gambia (the)', code: 'GM', flag: '🇬🇲', elo: 32 },
  { name: 'Georgia', code: 'GE', flag: '🇬🇪', elo: 50 },
  { name: 'Germany', code: 'DE', flag: '🇩🇪', elo: 89 },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭', elo: 74 },
  { name: 'Gibraltar', code: 'GI', flag: '🇬🇮', elo: 59 },
  { name: 'Greece', code: 'GR', flag: '🇬🇷', elo: 74 },
  { name: 'Greenland', code: 'GL', flag: '🇬🇱', elo: 41 },
  { name: 'Grenada', code: 'GD', flag: '🇬🇩', elo: 57 },
  { name: 'Guadeloupe', code: 'GP', flag: '🇬🇵', elo: 65 },
  { name: 'Guam', code: 'GU', flag: '🇬🇺', elo: 43 },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹', elo: 34 },
  { name: 'Guernsey', code: 'GG', flag: '🇬🇬', elo: 43 },
  { name: 'Guinea', code: 'GN', flag: '🇬🇳', elo: 36 },
  { name: 'Guinea-Bissau', code: 'GW', flag: '🇬🇼', elo: 53 },
  { name: 'Guyana', code: 'GY', flag: '🇬🇾', elo: 41 },
  { name: 'Haiti', code: 'HT', flag: '🇭🇹', elo: 40 },
  { name: 'Heard Island and McDonald Islands', code: 'HM', flag: '🇭🇲', elo: 47 },
  { name: 'Holy See (the)', code: 'VA', flag: '🇻🇦', elo: 35 },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳', elo: 71 },
  { name: 'Hong Kong', code: 'HK', flag: '🇭🇰', elo: 51 },
  { name: 'Hungary', code: 'HU', flag: '🇭🇺', elo: 78 },
  { name: 'Iceland', code: 'IS', flag: '🇮🇸', elo: 72 },
  { name: 'India', code: 'IN', flag: '🇮🇳', elo: 34 },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩', elo: 61 },
  { name: 'Iran (Islamic Republic of)', code: 'IR', flag: '🇮🇷', elo: 42 },
  { name: 'Iraq', code: 'IQ', flag: '🇮🇶', elo: 72 },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪', elo: 64 },
  { name: 'Isle of Man', code: 'IM', flag: '🇮🇲', elo: 39 },
  { name: 'Israel', code: 'IL', flag: '🇮🇱', elo: 50 },
  { name: 'Italy', code: 'IT', flag: '🇮🇹', elo: 90 },
  { name: 'Jamaica', code: 'JM', flag: '🇯🇲', elo: 70 },
  { name: 'Japan', code: 'JP', flag: '🇯🇵', elo: 82 },
  { name: 'Jersey', code: 'JE', flag: '🇯🇪', elo: 34 },
  { name: 'Jordan', code: 'JO', flag: '🇯🇴', elo: 65 },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', elo: 35 },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪', elo: 56 },
  { name: 'Kiribati', code: 'KI', flag: '🇰🇮', elo: 65 },
  { name: 'Korea (the Democratic People\'s Republic of)', code: 'KP', flag: '🇰🇵', elo: 46 },
  { name: 'Korea (the Republic of)', code: 'KR', flag: '🇰🇷', elo: 56 },
  { name: 'Kuwait', code: 'KW', flag: '🇰🇼', elo: 60 },
  { name: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', elo: 47 },
  { name: 'Lao People\'s Democratic Republic (the)', code: 'LA', flag: '🇱🇦', elo: 35 },
  { name: 'Latvia', code: 'LV', flag: '🇱🇻', elo: 38 },
  { name: 'Lebanon', code: 'LB', flag: '🇱🇧', elo: 44 },
  { name: 'Lesotho', code: 'LS', flag: '🇱🇸', elo: 41 },
  { name: 'Liberia', code: 'LR', flag: '🇱🇷', elo: 48 },
  { name: 'Libya', code: 'LY', flag: '🇱🇾', elo: 58 },
  { name: 'Liechtenstein', code: 'LI', flag: '🇱🇮', elo: 45 },
  { name: 'Lithuania', code: 'LT', flag: '🇱🇹', elo: 36 },
  { name: 'Luxembourg', code: 'LU', flag: '🇱🇺', elo: 37 },
  { name: 'Macao', code: 'MO', flag: '🇲🇴', elo: 64 },
  { name: 'Madagascar', code: 'MG', flag: '🇲🇬', elo: 46 },
  { name: 'Malawi', code: 'MW', flag: '🇲🇼', elo: 39 },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾', elo: 39 },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻', elo: 44 },
  { name: 'Mali', code: 'ML', flag: '🇲🇱', elo: 75 },
  { name: 'Malta', code: 'MT', flag: '🇲🇹', elo: 42 },
  { name: 'Marshall Islands (the)', code: 'MH', flag: '🇲🇭', elo: 50 },
  { name: 'Martinique', code: 'MQ', flag: '🇲🇶', elo: 61 },
  { name: 'Mauritania', code: 'MR', flag: '🇲🇷', elo: 55 },
  { name: 'Mauritius', code: 'MU', flag: '🇲🇺', elo: 41 },
  { name: 'Mayotte', code: 'YT', flag: '🇾🇹', elo: 45 },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽', elo: 80 },
  { name: 'Micronesia (Federated States of)', code: 'FM', flag: '🇫🇲', elo: 61 },
  { name: 'Moldova (the Republic of)', code: 'MD', flag: '🇲🇩', elo: 51 },
  { name: 'Monaco', code: 'MC', flag: '🇲🇨', elo: 62 },
  { name: 'Mongolia', code: 'MN', flag: '🇲🇳', elo: 36 },
  { name: 'Montenegro', code: 'ME', flag: '🇲🇪', elo: 69 },
  { name: 'Montserrat', code: 'MS', flag: '🇲🇸', elo: 52 },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦', elo: 85 },
  { name: 'Mozambique', code: 'MZ', flag: '🇲🇿', elo: 45 },
  { name: 'Myanmar', code: 'MM', flag: '🇲🇲', elo: 61 },
  { name: 'Namibia', code: 'NA', flag: '🇳🇦', elo: 65 },
  { name: 'Nauru', code: 'NR', flag: '🇳🇷', elo: 36 },
  { name: 'Nepal', code: 'NP', flag: '🇳🇵', elo: 60 },
  { name: 'Netherlands (Kingdom of the)', code: 'NL', flag: '🇳🇱', elo: 45 },
  { name: 'New Caledonia', code: 'NC', flag: '🇳🇨', elo: 47 },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿', elo: 68 },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮', elo: 60 },
  { name: 'Niger (the)', code: 'NE', flag: '🇳🇪', elo: 59 },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬', elo: 78 },
  { name: 'Niue', code: 'NU', flag: '🇳🇺', elo: 55 },
  { name: 'Norfolk Island', code: 'NF', flag: '🇳🇫', elo: 59 },
  { name: 'North Macedonia', code: 'MK', flag: '🇲🇰', elo: 70 },
  { name: 'Northern Mariana Islands (the)', code: 'MP', flag: '🇲🇵', elo: 38 },
  { name: 'Norway', code: 'NO', flag: '🇳🇴', elo: 76 },
  { name: 'Oman', code: 'OM', flag: '🇴🇲', elo: 69 },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰', elo: 55 },
  { name: 'Palau', code: 'PW', flag: '🇵🇼', elo: 42 },
  { name: 'Palestine, State of', code: 'PS', flag: '🇵🇸', elo: 41 },
  { name: 'Panama', code: 'PA', flag: '🇵🇦', elo: 70 },
  { name: 'Papua New Guinea', code: 'PG', flag: '🇵🇬', elo: 42 },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾', elo: 73 },
  { name: 'Peru', code: 'PE', flag: '🇵🇪', elo: 77 },
  { name: 'Philippines (the)', code: 'PH', flag: '🇵🇭', elo: 49 },
  { name: 'Pitcairn', code: 'PN', flag: '🇵🇳', elo: 47 },
  { name: 'Poland', code: 'PL', flag: '🇵🇱', elo: 78 },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹', elo: 91 },
  { name: 'Puerto Rico', code: 'PR', flag: '🇵🇷', elo: 48 },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦', elo: 73 },
  { name: 'Réunion', code: 'RE', flag: '🇷🇪', elo: 44 },
  { name: 'Romania', code: 'RO', flag: '🇷🇴', elo: 75 },
  { name: 'Russian Federation (the)', code: 'RU', flag: '🇷🇺', elo: 38 },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼', elo: 39 },
  { name: 'Saint Barthélemy', code: 'BL', flag: '🇧🇱', elo: 44 },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', code: 'SH', flag: '🇸🇭', elo: 38 },
  { name: 'Saint Kitts and Nevis', code: 'KN', flag: '🇰🇳', elo: 50 },
  { name: 'Saint Lucia', code: 'LC', flag: '🇱🇨', elo: 57 },
  { name: 'Saint Martin (French part)', code: 'MF', flag: '🇲🇫', elo: 36 },
  { name: 'Saint Pierre and Miquelon', code: 'PM', flag: '🇵🇲', elo: 64 },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', flag: '🇻🇨', elo: 47 },
  { name: 'Samoa', code: 'WS', flag: '🇼🇸', elo: 42 },
  { name: 'San Marino', code: 'SM', flag: '🇸🇲', elo: 32 },
  { name: 'Sao Tome and Principe', code: 'ST', flag: '🇸🇹', elo: 41 },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', elo: 74 },
  { name: 'Senegal', code: 'SN', flag: '🇸🇳', elo: 84 },
  { name: 'Serbia', code: 'RS', flag: '🇷🇸', elo: 78 },
  { name: 'Seychelles', code: 'SC', flag: '🇸🇨', elo: 49 },
  { name: 'Sierra Leone', code: 'SL', flag: '🇸🇱', elo: 42 },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬', elo: 41 },
  { name: 'Sint Maarten (Dutch part)', code: 'SX', flag: '🇸🇽', elo: 33 },
  { name: 'Slovakia', code: 'SK', flag: '🇸🇰', elo: 74 },
  { name: 'Slovenia', code: 'SI', flag: '🇸🇮', elo: 72 },
  { name: 'Solomon Islands', code: 'SB', flag: '🇸🇧', elo: 65 },
  { name: 'Somalia', code: 'SO', flag: '🇸🇴', elo: 56 },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦', elo: 73 },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS', flag: '🇬🇸', elo: 62 },
  { name: 'South Sudan', code: 'SS', flag: '🇸🇸', elo: 46 },
  { name: 'Spain', code: 'ES', flag: '🇪🇸', elo: 92 },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', elo: 52 },
  { name: 'Sudan (the)', code: 'SD', flag: '🇸🇩', elo: 43 },
  { name: 'Suriname', code: 'SR', flag: '🇸🇷', elo: 30 },
  { name: 'Svalbard and Jan Mayen', code: 'SJ', flag: '🇸🇯', elo: 44 },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪', elo: 78 },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭', elo: 83 },
  { name: 'Syrian Arab Republic (the)', code: 'SY', flag: '🇸🇾', elo: 52 },
  { name: 'Taiwan (Province of China)', code: 'TW', flag: '🇹🇼', elo: 49 },
  { name: 'Tajikistan', code: 'TJ', flag: '🇹🇯', elo: 40 },
  { name: 'Tanzania, the United Republic of', code: 'TZ', flag: '🇹🇿', elo: 55 },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭', elo: 55 },
  { name: 'Timor-Leste', code: 'TL', flag: '🇹🇱', elo: 43 },
  { name: 'Togo', code: 'TG', flag: '🇹🇬', elo: 48 },
  { name: 'Tokelau', code: 'TK', flag: '🇹🇰', elo: 52 },
  { name: 'Tonga', code: 'TO', flag: '🇹🇴', elo: 64 },
  { name: 'Trinidad and Tobago', code: 'TT', flag: '🇹🇹', elo: 57 },
  { name: 'Tunisia', code: 'TN', flag: '🇹🇳', elo: 79 },
  { name: 'Türkiye', code: 'TR', flag: '🇹🇷', elo: 56 },
  { name: 'Turkmenistan', code: 'TM', flag: '🇹🇲', elo: 45 },
  { name: 'Turks and Caicos Islands (the)', code: 'TC', flag: '🇹🇨', elo: 65 },
  { name: 'Tuvalu', code: 'TV', flag: '🇹🇻', elo: 63 },
  { name: 'Uganda', code: 'UG', flag: '🇺🇬', elo: 40 },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦', elo: 79 },
  { name: 'United Arab Emirates (the)', code: 'AE', flag: '🇦🇪', elo: 31 },
  { name: 'United Kingdom of Great Britain and Northern Ireland (the)', code: 'GB', flag: '🇬🇧', elo: 60 },
  { name: 'United States Minor Outlying Islands (the)', code: 'UM', flag: '🇺🇲', elo: 41 },
  { name: 'United States of America (the)', code: 'US', flag: '🇺🇸', elo: 33 },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾', elo: 88 },
  { name: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', elo: 68 },
  { name: 'Vanuatu', code: 'VU', flag: '🇻🇺', elo: 44 },
  { name: 'Venezuela (Bolivarian Republic of)', code: 'VE', flag: '🇻🇪', elo: 36 },
  { name: 'Viet Nam', code: 'VN', flag: '🇻🇳', elo: 57 },
  { name: 'Virgin Islands (British)', code: 'VG', flag: '🇻🇬', elo: 44 },
  { name: 'Virgin Islands (U.S.)', code: 'VI', flag: '🇻🇮', elo: 38 },
  { name: 'Wallis and Futuna', code: 'WF', flag: '🇼🇫', elo: 31 },
  { name: 'Western Sahara*', code: 'EH', flag: '🇪🇭', elo: 34 },
  { name: 'Yemen', code: 'YE', flag: '🇾🇪', elo: 39 },
  { name: 'Zambia', code: 'ZM', flag: '🇿🇲', elo: 32 },
  { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', elo: 43 }
];
